version: '3.1'

services:

  my-mongo-db:
    container_name: my-database
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678*
      MONGO_INITDB_DATABASE: Library
    ports:
      - "27017:27017"
    volumes:
      - /home/margus/Desktop/database-mongo/:/data/db
      - /home/margus/Desktop/bootcamp-3-challenge/reto6-bonus/Json/:/data/collection/
      - /home/margus/Desktop/bootcamp-3-challenge/reto6-bonus/Import/:/docker-entrypoint-initdb.d/


  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345678*
      ME_CONFIG_MONGODB_URL: mongodb://root:12345678@my-mongo-db:27017/


  my-nginx:
    container_name: bootcamp-web
    image: nginx
    ports:
      - "9999:80"
    volumes:
      - /home/margus/Desktop/bootcamp-3-challenge/reto6-bonus/bootcamp-web/:/usr/share/nginx/html/
  

